const categories = [
    { id: 'hashing', name: 'Hashing', icon: 'hash' },
    { id: 'encoding', name: 'Encoding', icon: 'binary' },
    { id: 'crypto', name: 'Cryptography', icon: 'lock' },
    { id: 'formatters', name: 'Formatters', icon: 'file-code' },
    { id: 'generators', name: 'Generators', icon: 'sparkles' },
    { id: 'converters', name: 'Converters', icon: 'refresh-cw' },
    { id: 'dev-utils', name: 'Dev Utilities', icon: 'terminal' },
    { id: 'text-tools', name: 'Text Tools', icon: 'type' }
];

const toolsRegistry = [
    // Hashing
    { id: 'md5', category: 'hashing', title: 'MD5', description: 'Message Digest Algorithm 5', icon: 'hash' },
    { id: 'sha1', category: 'hashing', title: 'SHA-1', description: 'Secure Hash Algorithm 1', icon: 'hash' },
    { id: 'sha256', category: 'hashing', title: 'SHA-256', description: 'Secure Hash Algorithm 256-bit', icon: 'hash' },
    { id: 'sha512', category: 'hashing', title: 'SHA-512', description: 'Secure Hash Algorithm 512-bit', icon: 'hash' },
    { id: 'sha384', category: 'hashing', title: 'SHA-384', description: 'Secure Hash Algorithm 384-bit', icon: 'hash' },
    { id: 'sha3-256', category: 'hashing', title: 'SHA3-256', description: 'Keccak-based SHA-3 256-bit', icon: 'hash' },
    { id: 'sha3-512', category: 'hashing', title: 'SHA3-512', description: 'Keccak-based SHA-3 512-bit', icon: 'hash' },
    { id: 'keccak-256', category: 'hashing', title: 'Keccak-256', description: 'Ethereum-style Keccak-256', icon: 'hash' },
    { id: 'ripemd160', category: 'hashing', title: 'RIPEMD-160', description: 'Race Integrity Primitives Evaluation Message Digest', icon: 'hash' },
    { id: 'hmac-sha256', category: 'hashing', title: 'HMAC-SHA256', description: 'Hash-based Message Authentication Code', icon: 'key' },
    { id: 'hmac-sha512', category: 'hashing', title: 'HMAC-SHA512', description: 'Hash-based Message Authentication Code', icon: 'key' },
    { id: 'crc32', category: 'hashing', title: 'CRC32', description: 'Cyclic Redundancy Check', icon: 'hash' },
    { id: 'whirlpool', category: 'hashing', title: 'Whirlpool', description: 'Whirlpool hash algorithm', icon: 'hash' },
    { id: 'adler32', category: 'hashing', title: 'Adler-32', description: 'Adler-32 checksum', icon: 'hash' },

    // Encoding
    { id: 'base64-encode', category: 'encoding', title: 'Base64 Encode', description: 'Encode text to Base64', icon: 'binary' },
    { id: 'base64-decode', category: 'encoding', title: 'Base64 Decode', description: 'Decode Base64 to text', icon: 'binary' },
    { id: 'base64url-encode', category: 'encoding', title: 'Base64URL Encode', description: 'URL-safe Base64 encoding', icon: 'link' },
    { id: 'base64url-decode', category: 'encoding', title: 'Base64URL Decode', description: 'URL-safe Base64 decoding', icon: 'link' },
    { id: 'hex-encode', category: 'encoding', title: 'Hex Encode', description: 'Encode text to Hex', icon: 'code' },
    { id: 'hex-decode', category: 'encoding', title: 'Hex Decode', description: 'Decode Hex to text', icon: 'code' },
    { id: 'url-encode', category: 'encoding', title: 'URL Encode', description: 'Percent-encoding for URLs', icon: 'link' },
    { id: 'url-decode', category: 'encoding', title: 'URL Decode', description: 'Decode percent-encoded URLs', icon: 'link' },
    { id: 'html-encode', category: 'encoding', title: 'HTML Encode', description: 'Encode HTML entities', icon: 'code' },
    { id: 'html-decode', category: 'encoding', title: 'HTML Decode', description: 'Decode HTML entities', icon: 'code' },
    { id: 'binary-encode', category: 'encoding', title: 'Binary Encode', description: 'Convert text to binary', icon: 'cpu' },
    { id: 'binary-decode', category: 'encoding', title: 'Binary Decode', description: 'Convert binary to text', icon: 'cpu' },
    { id: 'base32-encode', category: 'encoding', title: 'Base32 Encode', description: 'Encode text to Base32', icon: 'binary' },
    { id: 'base32-decode', category: 'encoding', title: 'Base32 Decode', description: 'Decode Base32 to text', icon: 'binary' },
    { id: 'base58-encode', category: 'encoding', title: 'Base58 Encode', description: 'Encode text to Base58 (Bitcoin style)', icon: 'bitcoin' },
    { id: 'morse-encode', category: 'encoding', title: 'Morse Code Encode', description: 'Text to Morse code', icon: 'radio' },
    { id: 'morse-decode', category: 'encoding', title: 'Morse Code Decode', description: 'Morse code to text', icon: 'radio' },
    { id: 'rot13', category: 'encoding', title: 'ROT13', description: 'Rotate by 13 places', icon: 'refresh-cw' },
    { id: 'rot47', category: 'encoding', title: 'ROT47', description: 'Rotate by 47 places', icon: 'refresh-cw' },

    // Cryptography
    { id: 'aes-encrypt', category: 'crypto', title: 'AES Encrypt', description: 'Advanced Encryption Standard', icon: 'lock' },
    { id: 'aes-decrypt', category: 'crypto', title: 'AES Decrypt', description: 'Decrypt AES content', icon: 'unlock' },
    { id: 'triple-des-encrypt', category: 'crypto', title: 'Triple DES Encrypt', description: 'Triple Data Encryption Standard', icon: 'lock' },
    { id: 'triple-des-decrypt', category: 'crypto', title: 'Triple DES Decrypt', description: 'Decrypt 3DES content', icon: 'unlock' },
    { id: 'rc4-encrypt', category: 'crypto', title: 'RC4 Encrypt', description: 'RC4 stream cipher', icon: 'lock' },
    { id: 'rc4-decrypt', category: 'crypto', title: 'RC4 Decrypt', description: 'Decrypt RC4 content', icon: 'unlock' },
    { id: 'rabbit-encrypt', category: 'crypto', title: 'Rabbit Encrypt', description: 'Rabbit stream cipher', icon: 'lock' },
    { id: 'rabbit-decrypt', category: 'crypto', title: 'Rabbit Decrypt', description: 'Decrypt Rabbit content', icon: 'unlock' },
    { id: 'password-gen', category: 'crypto', title: 'Password Generator', description: 'Secure random password generator', icon: 'key' },
    { id: 'bitcoin-gen', category: 'crypto', title: 'BTC Address Gen', description: 'Generate Bitcoin address from seed', icon: 'bitcoin' },
    { id: 'uuid-v4', category: 'crypto', title: 'UUID v4 Generator', description: 'Random Unique Identifier', icon: 'fingerprint' },
    { id: 'pbkdf2-gen', category: 'crypto', title: 'PBKDF2 Hash', description: 'Password-Based Key Derivation Function 2', icon: 'key' },

    // Formatters
    { id: 'json-format', category: 'formatters', title: 'JSON Formatter', description: 'Prettify JSON strings', icon: 'file-json' },
    { id: 'json-minify', category: 'formatters', title: 'JSON Minifier', description: 'Compact JSON strings', icon: 'file-json' },
    { id: 'xml-format', category: 'formatters', title: 'XML Formatter', description: 'Prettify XML content', icon: 'file-code' },
    { id: 'html-format', category: 'formatters', title: 'HTML Formatter', description: 'Prettify HTML code', icon: 'file-code' },
    { id: 'css-format', category: 'formatters', title: 'CSS Formatter', description: 'Prettify CSS code', icon: 'file-code' },
    { id: 'js-format', category: 'formatters', title: 'JS Formatter', description: 'Prettify JavaScript code', icon: 'file-code' },
    { id: 'yaml-json', category: 'formatters', title: 'YAML to JSON', description: 'Convert YAML to JSON', icon: 'repeat' },
    { id: 'json-yaml', category: 'formatters', title: 'JSON to YAML', description: 'Convert JSON to YAML', icon: 'repeat' },
    { id: 'csv-json', category: 'formatters', title: 'CSV to JSON', description: 'Convert CSV to JSON', icon: 'table' },
    { id: 'json-csv', category: 'formatters', title: 'JSON to CSV', description: 'Convert JSON to CSV', icon: 'table' },

    // Converters
    { id: 'unix-timestamp', category: 'converters', title: 'Unix Timestamp', description: 'Convert Epoch to Date', icon: 'clock' },
    { id: 'date-unix', category: 'converters', title: 'Date to Unix', description: 'Convert Date to Epoch', icon: 'calendar' },
    { id: 'base-converter', category: 'converters', title: 'Base Converter', description: 'Convert between Dec, Hex, Bin, Oct', icon: 'binary' },
    { id: 'color-converter', category: 'converters', title: 'Color Converter', description: 'HEX, RGB, HSL conversion', icon: 'palette' },
    { id: 'length-converter', category: 'converters', title: 'Length Converter', description: 'Metric and Imperial conversion', icon: 'ruler' },
    { id: 'weight-converter', category: 'converters', title: 'Weight Converter', description: 'Mass conversion', icon: 'anvil' },
    { id: 'temp-converter', category: 'converters', title: 'Temp Converter', description: 'Celsius, Fahrenheit, Kelvin', icon: 'thermometer' },
    { id: 'byte-converter', category: 'converters', title: 'Byte Converter', description: 'B, KB, MB, GB, TB conversion', icon: 'hard-drive' },
    { id: 'bin-dec', category: 'converters', title: 'Binary to Decimal', description: 'Base 2 to Base 10', icon: 'binary' },
    { id: 'dec-bin', category: 'converters', title: 'Decimal to Binary', description: 'Base 10 to Base 2', icon: 'binary' },
    { id: 'hex-dec', category: 'converters', title: 'Hex to Decimal', description: 'Base 16 to Base 10', icon: 'code' },
    { id: 'dec-hex', category: 'converters', title: 'Decimal to Hex', description: 'Base 10 to Base 16', icon: 'code' },

    // Generators
    { id: 'lorem-ipsum', category: 'generators', title: 'Lorem Ipsum', description: 'Placeholder text generator', icon: 'align-left' },
    { id: 'qr-gen', category: 'generators', title: 'QR Code Gen', description: 'Generate QR codes', icon: 'qr-code' },
    { id: 'ulid-gen', category: 'generators', title: 'ULID Generator', description: 'Universally Unique Lexicographically Sortable Identifier', icon: 'clock' },
    { id: 'fake-data-gen', category: 'generators', title: 'Fake Data Gen', description: 'Generate names, addresses, emails', icon: 'user' },
    { id: 'secure-token-gen', category: 'generators', title: 'Secure Token Gen', description: 'Random secure token generator', icon: 'shield' },
    { id: 'credit-card-gen', category: 'generators', title: 'Credit Card Gen', description: 'Generate mock credit card numbers', icon: 'credit-card' },
    { id: 'mac-gen', category: 'generators', title: 'MAC Address Gen', description: 'Random MAC address generator', icon: 'network' },
    { id: 'docker-gen', category: 'generators', title: 'Docker Compose Gen', description: 'Basic Docker Compose template', icon: 'container' },

    // Dev Utils
    { id: 'jwt-decode', category: 'dev-utils', title: 'JWT Decoder', description: 'Decode JSON Web Tokens', icon: 'shield' },
    { id: 'user-agent', category: 'dev-utils', title: 'User Agent Parser', description: 'Parse browser user agents', icon: 'laptop' },
    { id: 'url-parser', category: 'dev-utils', title: 'URL Parser', description: 'Parse URL components', icon: 'link' },
    { id: 'http-status', category: 'dev-utils', title: 'HTTP Status Codes', description: 'Lookup HTTP codes', icon: 'server' },
    { id: 'ascii-hex', category: 'dev-utils', title: 'ASCII to Hex', description: 'Convert text to hex', icon: 'code' },
    { id: 'hex-ascii', category: 'dev-utils', title: 'Hex to ASCII', description: 'Convert hex to text', icon: 'code' },
    { id: 'diff-checker', category: 'dev-utils', title: 'Diff Checker', description: 'Compare two strings', icon: 'columns' },
    { id: 'markdown-preview', category: 'dev-utils', title: 'Markdown Preview', description: 'Live Markdown renderer', icon: 'file-text' },
    { id: 'json-validator', category: 'dev-utils', title: 'JSON Validator', description: 'Check if JSON is valid', icon: 'check-circle' },
    { id: 'yaml-validator', category: 'dev-utils', title: 'YAML Validator', description: 'Check if YAML is valid', icon: 'check-circle' },
    { id: 'html-to-markdown', category: 'dev-utils', title: 'HTML to Markdown', description: 'Convert HTML to MD', icon: 'file-text' },
    { id: 'markdown-to-html', category: 'dev-utils', title: 'Markdown to HTML', description: 'Convert MD to HTML', icon: 'file-code' },

    // Text Tools
    { id: 'case-converter', category: 'text-tools', title: 'Case Converter', description: 'UPPER, lower, TitleCase, etc.', icon: 'type' },
    { id: 'word-counter', category: 'text-tools', title: 'Word Counter', description: 'Count words, chars, lines', icon: 'list-ordered' },
    { id: 'reverse-text', category: 'text-tools', title: 'Reverse Text', description: 'Flip text backwards', icon: 'refresh-cw' },
    { id: 'sort-lines', category: 'text-tools', title: 'Sort Lines', description: 'Alphabetical line sort', icon: 'sort-asc' },
    { id: 'remove-duplicates', category: 'text-tools', title: 'Remove Duplicates', description: 'Remove duplicate lines', icon: 'trash-2' },
    { id: 'strip-whitespace', category: 'text-tools', title: 'Strip Whitespace', description: 'Remove extra spaces', icon: 'scissors' },
    { id: 'text-speech', category: 'text-tools', title: 'Text to Speech', description: 'Speak the input text', icon: 'volume-2' },
    { id: 'string-inspector', category: 'text-tools', title: 'String Inspector', description: 'Detailed string analysis', icon: 'eye' },
    { id: 'lorem-markdown', category: 'text-tools', title: 'Lorem Markdown', description: 'Markdown formatted lorem ipsum', icon: 'file-text' },
    { id: 'add-line-numbers', category: 'text-tools', title: 'Add Line Numbers', description: 'Prefix each line with its number', icon: 'list-ordered' },
    { id: 'remove-empty-lines', category: 'text-tools', title: 'Remove Empty Lines', description: 'Clean up text', icon: 'trash-2' },
    { id: 'extract-emails', category: 'text-tools', title: 'Extract Emails', description: 'Find all emails in text', icon: 'mail' },
    { id: 'extract-urls', category: 'text-tools', title: 'Extract URLs', description: 'Find all URLs in text', icon: 'link' },
    { id: 'text-to-hex-array', category: 'text-tools', title: 'Text to Hex Array', description: 'Convert text to C-style hex array', icon: 'code' },
    { id: 'lorem-ipsum-text', category: 'text-tools', title: 'Lorem Ipsum Text', description: 'Plain text placeholder', icon: 'align-left' }
];
